# Publishes the npm package to GitHub Packages when you publish a GitHub Release.
# See: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry
# and: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

name: Publish to GitHub Packages

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: https://npm.pkg.github.com
          scope: "@hoseinmohajer"

      - name: Install dependencies
        run: npm install

      - name: Publish to GitHub Packages
        run: npm publish --userconfig ./.npmrc.gpr
